server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/sgra_db
spring.datasource.username=sgra_user
spring.datasource.password=Sgra2026*
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# JWT (HS256) -> mínimo 32 caracteres
app.jwt.secret=sgra_super_secret_key_32_chars_minimum_123456
app.jwt.issuer=sgra-api
app.jwt.exp-minutes=240

# sgra.reflection.demo=false